import asyncio
import aiohttp
import yt_dlp
import re
import json
import tempfile
import os
import time
from typing import Dict, List, Optional, Tuple
from pathlib import Path
import logging
from config import config_manager

class VideoAcquisition:
    def __init__(self):
        self.config = config_manager.get_video_config()
        self.session = None
        self.logger = logging.getLogger(__name__)
    
    def _convert_json_cookies_to_netscape(self, json_cookies_path: str) -> str:
        """
        Convert JSON cookies to Netscape cookie format that yt-dlp can use
        Returns path to temporary cookie file
        """
        if not os.path.exists(json_cookies_path):
            return None
        
        with open(json_cookies_path, 'r', encoding='utf-8') as f:
            cookies = json.load(f)
        
        # Create a temporary file for the cookies in Netscape format
        cookie_file = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.txt')
        
        # Write Netscape cookie format header
        cookie_file.write("# Netscape HTTP Cookie File\n")
        cookie_file.write("# This file was generated by video_acquisition.py\n")
        cookie_file.write("# Do not edit this file manually\n\n")
        
        # Check if required cookies exist, especially s_v_web_id for Douyin
        has_s_v_web_id = any(cookie.get('name') == 's_v_web_id' for cookie in cookies)
        has_ttwid = any(cookie.get('name') == 'ttwid' for cookie in cookies)
        
        # If we don't have the required cookies for Douyin, we'll still process what we have
        # but log a warning
        if not has_s_v_web_id:
            self.logger.warning("Missing required 's_v_web_id' cookie for Douyin")
            # Generate a fake s_v_web_id cookie if missing - this might help bypass the check
            self._add_fallback_s_v_web_id_cookie(cookie_file)
        if not has_ttwid:
            self.logger.warning("Missing 'ttwid' cookie which may be required for Douyin")
        
        for cookie in cookies:
            domain = cookie.get('domain', '')
            # The flag should be TRUE if the domain starts with a dot (allow subdomains)
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            
            # Handle expires value - if it's -1 (session cookie), set to a future date
            expires_raw = cookie.get('expires', 0)
            if expires_raw == -1 or expires_raw is None:
                # For session cookies or missing expires, set to a reasonable future time (e.g., 1 year from now)
                expires = str(int(time.time()) + 365 * 24 * 60 * 60)  # 1 year in seconds
            elif isinstance(expires_raw, (int, float)) and expires_raw > 0:
                # If the cookie is not expired, use its expiration time
                current_time = time.time()
                if expires_raw > current_time:
                    expires = str(int(expires_raw))
                else:
                    # Cookie is expired, set to a future time
                    expires = str(int(current_time + 365 * 24 * 60 * 60))
            else:
                # For other cases, set to a future time
                expires = str(int(time.time()) + 365 * 24 * 60 * 60)
            
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            
            # Skip cookies without essential fields
            if not name or not value:
                continue
                
            # Write the cookie in Netscape format
            cookie_line = f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
            cookie_file.write(cookie_line)
        
        cookie_file.close()
        return cookie_file.name
    
    def _add_fallback_s_v_web_id_cookie(self, cookie_file):
        """
        Add a fallback s_v_web_id cookie that might help bypass the requirement check
        """
        import random
        import string
        
        # Generate a fake but plausible s_v_web_id value
        # This is typically a verification ID for web sessions
        chars = string.ascii_letters + string.digits
        s_v_web_id_value = 'verify_' + ''.join(random.choice(chars) for _ in range(19)) + '_' + ''.join(random.choice(chars) for _ in range(10))
        
        # Write the cookie in Netscape format
        cookie_line = f".douyin.com\tTRUE\t/\tFALSE\t{int(time.time()) + 365 * 24 * 60 * 60}\ts_v_web_id\t{s_v_web_id_value}\n"
        cookie_file.write(cookie_line)
    
    def check_cookies_validity(self, cookies_path: str = 'douyin_cookies.json') -> bool:
        """
        检查cookies文件是否存在且包含必要的cookie
        对于抖音，需要检查是否包含登录相关的关键cookie
        """
        if not os.path.exists(cookies_path):
            self.logger.warning(f"Cookies文件不存在: {cookies_path}")
            return False
        
        try:
            with open(cookies_path, 'r', encoding='utf-8') as f:
                cookies = json.load(f)
            
            if not cookies:
                self.logger.warning("Cookies文件为空")
                return False
            
            # 检查是否有过期的cookies
            current_time = time.time()
            valid_cookies = []
            
            for cookie in cookies:
                expires = cookie.get('expires', 0)
                # 如果expires为-1表示会话cookie，通常认为是有效的
                if expires == -1:
                    valid_cookies.append(cookie)
                elif isinstance(expires, (int, float)) and expires > current_time:
                    valid_cookies.append(cookie)
                elif expires == 0 or expires is None:
                    # 没有设置过期时间的cookie，认为是有效的
                    valid_cookies.append(cookie)
            
            # 检查是否包含抖音登录所需的关键cookies
            # 抖音需要登录状态的cookies，包括 sessionid, sessionid_ss, passport_csrf_token 等
            required_cookies = ['sessionid', 'sessionid_ss', 'passport_csrf_token', 'sid_guard']
            has_login_cookies = any(cookie.get('name') in required_cookies for cookie in valid_cookies)
            
            # 检查其他重要的cookies
            has_s_v_web_id = any(cookie.get('name') == 's_v_web_id' for cookie in valid_cookies)
            has_ttwid = any(cookie.get('name') == 'ttwid' for cookie in valid_cookies)
            
            if not has_login_cookies:
                self.logger.warning("缺少抖音登录所需的关键cookies (sessionid, sessionid_ss, passport_csrf_token, sid_guard)")
                # 如果没有登录cookies，即使有其他cookies也认为无效
                return False
            
            if not has_s_v_web_id:
                self.logger.warning("缺少关键的s_v_web_id cookie")
            
            if not has_ttwid:
                self.logger.warning("缺少ttwid cookie")
            
            # 如果有至少一些有效的cookies，我们认为cookies文件是有效的
            return len(valid_cookies) > 0
            
        except Exception as e:
            self.logger.error(f"检查cookies有效性时出错: {e}")
            return False

    def suggest_refresh_cookies(self):
        """
        建议用户刷新cookies
        """
        print("提示：当前cookies可能已失效，请运行以下命令重新获取cookies：")
        print("python manual_login.py")
        self.logger.info("检测到cookies可能已失效，建议重新登录获取新的cookies")
    
    async def refresh_cookies_if_needed(self, force_refresh: bool = False):
        """
        检查并刷新cookies，如果需要的话
        force_refresh: 强制刷新cookies，即使本地检查认为有效
        
        注意：此方法现在只是提示用户手动运行 manual_login.py
        因为自动登录脚本可能无法正确获取登录 cookies
        """
        cookies_exist = os.path.exists('douyin_cookies.json')
        
        # 检查cookies有效性
        cookies_valid = self.check_cookies_validity() if cookies_exist else False
        
        # 如果强制刷新、cookies不存在或cookies无效，则提示用户手动登录
        if force_refresh or not cookies_exist or not cookies_valid:
            print("检测到cookies需要刷新...")
            print("=" * 60)
            print("请手动运行以下命令来获取新的 cookies：")
            print("python manual_login.py")
            print("=" * 60)
            print("\n操作步骤：")
            print("1. 运行上述命令后，浏览器会自动打开")
            print("2. 在浏览器中完成登录操作（扫码或手机号）")
            print("3. 登录成功后，在此终端按回车键保存 cookies")
            print("=" * 60)
            
            self.logger.info("提示用户手动登录获取新cookies")
            return False
        else:
            print("当前cookies仍有效，无需刷新")
            return True
    
    async def __aenter__(self):
        self.session = aiohttp.ClientSession()
        return self
    
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self.session:
            await self.session.close()
    
    async def resolve_short_url(self, short_url: str) -> Optional[str]:
        """将短链接转换为长链接"""
        try:
            if not short_url.startswith(('http://', 'https://')):
                short_url = 'https://' + short_url
            
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
                'Accept-Encoding': 'gzip, deflate, br',
                'Connection': 'keep-alive',
            }
            
            async with aiohttp.ClientSession() as session:
                async with session.get(short_url, headers=headers, allow_redirects=True, timeout=aiohttp.ClientTimeout(total=10)) as response:
                    if response.status == 200:
                        long_url = str(response.url)
                        self.logger.info(f"短链接转换成功: {short_url} -> {long_url}")
                        return long_url
                    else:
                        self.logger.warning(f"短链接转换失败，状态码: {response.status}")
                        return None
        except Exception as e:
            self.logger.error(f"短链接转换出错: {e}")
            return None

    def extract_platform_and_id(self, url: str) -> Optional[Tuple[str, str]]:
        """从URL提取平台和视频ID"""
        # 抖音URL模式
        douyin_patterns = [
            r'douyin\.com/(\w+)',
            r'douyin\.com.*video/(\w+)',
            r'v\.douyin\.com/(\w+)',
            r'v\.douyin\.com/(\w+)/'
        ]
        
        # 快手URL模式
        kuaishou_patterns = [
            r'kuaishou\.com/(\w+)',
            r'kuaishou\.com/.*photoId=(\w+)',
            r'gifshow\.com/(\w+)',
            r'gifshow\.com/.*photoId=(\w+)'
        ]
        
        for pattern in douyin_patterns:
            match = re.search(pattern, url)
            if match:
                return 'douyin', match.group(1)
        
        for pattern in kuaishou_patterns:
            match = re.search(pattern, url)
            if match:
                return 'kuaishou', match.group(1)
        
        return None
    
    async def get_video_info(self, url: str, use_cookies: bool = True) -> Optional[Dict]:
        """获取视频信息"""
        # 检查是否为短链接，如果是则先转换为长链接
        if 'v.douyin.com' in url or 'v.kuaishou.com' in url or 'gifshow.com' in url:
            self.logger.info(f"检测到短链接，尝试转换: {url}")
            resolved_url = await self.resolve_short_url(url)
            if resolved_url:
                url = resolved_url
                self.logger.info(f"短链接转换成功，使用长链接: {url}")
            else:
                self.logger.warning(f"短链接转换失败，继续使用原链接: {url}")
        
        platform_video = self.extract_platform_and_id(url)
        if not platform_video:
            self.logger.error(f"无法识别的视频平台: {url}")
            return None
        
        platform, video_id = platform_video
        
        # 检查cookies有效性
        cookies_valid = self.check_cookies_validity() if use_cookies else False
        
        # 如果cookies无效且用户希望使用cookies，尝试刷新cookies
        if use_cookies and not cookies_valid:
            self.logger.info("检测到cookies无效，尝试自动刷新...")
            await self.refresh_cookies_if_needed()
            # 重新检查cookies有效性
            cookies_valid = self.check_cookies_validity()
        
        # 尝试使用cookies获取视频信息
        if use_cookies and cookies_valid:
            # 使用更完整的Douyin特定参数
            ydl_opts_with_cookies = {
                'quiet': True,
                'no_warnings': True,
                'extract_flat': True,
                'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'compat_opts': ['no-live-chat'],
                'extractor_args': {
                    'douyin': {
                        'app_version': '23.7.0',
                        'version_code': '2370',
                        'device_id': '7308818885086243331',  # 模拟设备ID
                        'iid': '7308818885086243331',  # 模拟安装ID
                        'openudid': '123456789abcdef0',  # 模拟openudid
                    }
                },
            }
            
            temp_cookie_file = self._convert_json_cookies_to_netscape('douyin_cookies.json')
            if temp_cookie_file:
                ydl_opts_with_cookies['cookiefile'] = temp_cookie_file
                # 添加更完整的头部信息，模拟真实浏览器请求
                ydl_opts_with_cookies['http_headers'] = {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    'Referer': 'https://www.douyin.com/',
                    'Origin': 'https://www.douyin.com',
                    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                    'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
                    'Accept-Encoding': 'gzip, deflate, br',
                    'Connection': 'keep-alive',
                    'Upgrade-Insecure-Requests': '1',
                    'Sec-Fetch-Dest': 'document',
                    'Sec-Fetch-Mode': 'navigate',
                    'Sec-Fetch-Site': 'none',
                    'Cache-Control': 'max-age=0',
                }
                # 添加额外的请求选项
                ydl_opts_with_cookies['headers'] = ydl_opts_with_cookies['http_headers']
        
            try:
                with yt_dlp.YoutubeDL(ydl_opts_with_cookies) as ydl:
                    info = ydl.extract_info(url, download=False)
                    
                    return {
                        'platform': platform,
                        'video_id': video_id,
                        'title': info.get('title', ''),
                        'author': info.get('uploader', ''),
                        'url': url,
                        'duration': info.get('duration', 0),
                        'thumbnail': info.get('thumbnail', ''),
                        'description': info.get('description', ''),
                        'upload_date': info.get('upload_date', ''),
                        'view_count': info.get('view_count', 0),
                        'like_count': info.get('like_count', 0),
                        'comment_count': info.get('comment_count', 0),
                    }
            except Exception as e:
                self.logger.warning(f"使用cookies获取视频信息失败: {e}")
                # 清理临时cookie文件
                if temp_cookie_file and os.path.exists(temp_cookie_file):
                    try:
                        os.unlink(temp_cookie_file)
                    except:
                        pass
                # 如果是由于cookies过期导致的错误，尝试自动刷新cookies
                if "Fresh cookies" in str(e) or "fresh cookies" in str(e):
                    self.logger.info("检测到cookies过期错误，尝试强制刷新...")
                    # 强制刷新cookies，即使本地检查认为有效
                    success = await self.refresh_cookies_if_needed(force_refresh=True)
                    if success:
                        # 刷新成功后，再次尝试使用cookies
                        temp_cookie_file = self._convert_json_cookies_to_netscape('douyin_cookies.json')
                        if temp_cookie_file:
                            ydl_opts_with_cookies['cookiefile'] = temp_cookie_file
                            # 添加更完整的头部信息
                            ydl_opts_with_cookies['http_headers'] = {
                                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                                'Referer': 'https://www.douyin.com/',
                                'Origin': 'https://www.douyin.com',
                                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                                'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
                                'Accept-Encoding': 'gzip, deflate, br',
                                'Connection': 'keep-alive',
                                'Upgrade-Insecure-Requests': '1',
                                'Sec-Fetch-Dest': 'document',
                                'Sec-Fetch-Mode': 'navigate',
                                'Sec-Fetch-Site': 'none',
                                'Cache-Control': 'max-age=0',
                            }
                            ydl_opts_with_cookies['headers'] = ydl_opts_with_cookies['http_headers']
                            
                            try:
                                with yt_dlp.YoutubeDL(ydl_opts_with_cookies) as ydl:
                                    info = ydl.extract_info(url, download=False)
                                    
                                    return {
                                        'platform': platform,
                                        'video_id': video_id,
                                        'title': info.get('title', ''),
                                        'author': info.get('uploader', ''),
                                        'url': url,
                                        'duration': info.get('duration', 0),
                                        'thumbnail': info.get('thumbnail', ''),
                                        'description': info.get('description', ''),
                                        'upload_date': info.get('upload_date', ''),
                                        'view_count': info.get('view_count', 0),
                                        'like_count': info.get('like_count', 0),
                                        'comment_count': info.get('comment_count', 0),
                                    }
                            except Exception as retry_e:
                                self.logger.warning(f"重试使用cookies获取视频信息也失败: {retry_e}")
                            finally:
                                # 清理临时cookie文件
                                if temp_cookie_file and os.path.exists(temp_cookie_file):
                                    try:
                                        os.unlink(temp_cookie_file)
                                    except:
                                        pass
                    
                    # 尝试不使用cookies
                    self.logger.info("尝试不使用cookies获取视频信息...")
        
        # 如果使用cookies失败或不使用cookies，尝试不使用cookies获取
        ydl_opts_no_cookies = {
            'quiet': True,
            'no_warnings': True,
            'extract_flat': True,
            'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'compat_opts': ['no-live-chat'],
            'extractor_args': {
                'douyin': {
                    'app_version': '23.7.0',
                    'version_code': '2370',
                    'web_session_id': 'fresh_session',
                    'device_id': '7308818885086243331',  # 模拟设备ID
                    'iid': '7308818885086243331',  # 模拟安装ID
                    'openudid': '123456789abcdef0',  # 模拟openudid
                }
            },
            'http_headers': {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Referer': 'https://www.douyin.com/',
                'Origin': 'https://www.douyin.com',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
                'Accept-Encoding': 'gzip, deflate, br',
                'Connection': 'keep-alive',
                'Upgrade-Insecure-Requests': '1',
                'Sec-Fetch-Dest': 'document',
                'Sec-Fetch-Mode': 'navigate',
                'Sec-Fetch-Site': 'none',
                'Cache-Control': 'max-age=0',
            },
        }
        
        try:
            with yt_dlp.YoutubeDL(ydl_opts_no_cookies) as ydl:
                info = ydl.extract_info(url, download=False)
                
                return {
                    'platform': platform,
                    'video_id': video_id,
                    'title': info.get('title', ''),
                    'author': info.get('uploader', ''),
                    'url': url,
                    'duration': info.get('duration', 0),
                    'thumbnail': info.get('thumbnail', ''),
                    'description': info.get('description', ''),
                    'upload_date': info.get('upload_date', ''),
                    'view_count': info.get('view_count', 0),
                    'like_count': info.get('like_count', 0),
                    'comment_count': info.get('comment_count', 0),
                }
        except Exception as e:
            self.logger.error(f"获取视频信息失败: {e}")
            # 如果是由于cookies过期导致的错误，提示用户重新登录
            if "Fresh cookies" in str(e) or "fresh cookies" in str(e):
                self.suggest_refresh_cookies()
                
                # 最后尝试使用Playwright作为备选方法
                print("尝试使用浏览器自动化方法获取视频信息...")
                playwright_result = await self.get_video_info_with_playwright(url)
                if playwright_result:
                    self.logger.info("成功通过浏览器自动化方法获取视频信息")
                    return playwright_result
            
            # 对于其他异常也尝试使用Playwright作为备选
            print("尝试使用浏览器自动化方法获取视频信息...")
            playwright_result = await self.get_video_info_with_playwright(url)
            if playwright_result:
                self.logger.info("成功通过浏览器自动化方法获取视频信息")
                return playwright_result
            
            return None
    
    async def get_video_info_with_playwright(self, url: str) -> Optional[Dict]:
        """使用Playwright获取视频信息作为备选方法"""
        try:
            from playwright.async_api import async_playwright
        except ImportError:
            self.logger.error("Playwright未安装，无法使用浏览器自动化方法获取视频信息")
            print("提示：需要安装playwright以使用浏览器自动化方法")
            print("请运行: pip install playwright")
            print("然后运行: playwright install chromium")
            return None
        
        # 检查是否为短链接，如果是则先转换为长链接
        if 'v.douyin.com' in url or 'v.kuaishou.com' in url or 'gifshow.com' in url:
            self.logger.info(f"检测到短链接，尝试转换: {url}")
            resolved_url = await self.resolve_short_url(url)
            if resolved_url:
                url = resolved_url
                self.logger.info(f"短链接转换成功，使用长链接: {url}")
            else:
                self.logger.warning(f"短链接转换失败，继续使用原链接: {url}")
        
        async with async_playwright() as p:
            try:
                print("正在启动浏览器以获取视频信息...")
                self.logger.info("启动浏览器以获取视频信息")
                
                browser = await p.chromium.launch(
                    headless=True,  # 使用无头模式
                    args=[
                        '--disable-blink-features=AutomationControlled',
                        '--disable-dev-shm-usage',
                        '--no-sandbox',
                        '--disable-blink-features',
                        '--disable-extensions',
                        '--disable-features=VizDisplayCompositor'
                    ]
                )
                
                # 设置更真实的浏览器上下文
                context = await browser.new_context(
                    viewport={'width': 1366, 'height': 768},
                    user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
                )
                
                # 隐藏 webdriver 特征
                await context.add_init_script("""
                    Object.defineProperty(navigator, 'webdriver', {
                        get: () => undefined,
                    });
                """)
                
                page = await context.new_page()
                
                print(f"正在访问视频页面: {url}")
                # 访问视频页面
                await page.goto(url, wait_until='domcontentloaded')
                
                # 等待页面加载
                await page.wait_for_timeout(5000)
                
                # 尝试获取视频标题
                video_title = await page.evaluate("""
                    () => {
                        // 尝试多种可能的选择器来获取视频标题
                        const selectors = [
                            '[data-e2e="video-title"]',
                            '.video-title',
                            '.desc',
                            '[class*="desc"]',
                            '.title',
                            'h1'
                        ];
                        
                        for (const selector of selectors) {
                            const element = document.querySelector(selector);
                            if (element) {
                                return element.innerText || element.textContent;
                            }
                        }
                        return null;
                    }
                """)
                
                # 尝试获取作者信息
                author_name = await page.evaluate("""
                    () => {
                        // 尝试多种可能的选择器来获取作者名称
                        const selectors = [
                            '[data-e2e="user-info"] .user-name',
                            '.user-info .name',
                            '[class*="user"] [class*="name"]',
                            '.author-name',
                            '.username'
                        ];
                        
                        for (const selector of selectors) {
                            const element = document.querySelector(selector);
                            if (element) {
                                return element.innerText || element.textContent;
                            }
                        }
                        return null;
                    }
                """)
                
                # 获取页面URL（可能已重定向）
                final_url = page.url
                
                # 提取视频ID
                import re
                video_id_match = re.search(r'/video/(\d+)', final_url)
                video_id = video_id_match.group(1) if video_id_match else None
                
                # 尝试获取视频时长等信息
                duration = 0  # Playwright方法暂时无法获取时长
                
                # 获取缩略图
                thumbnail = await page.evaluate("""
                    () => {
                        // 尝试获取缩略图
                        const selectors = [
                            'video',
                            'img[src*="cover"]',
                            'img[data-cover]',
                            '[class*="cover"] img'
                        ];
                        
                        for (const selector of selectors) {
                            const element = document.querySelector(selector);
                            if (element) {
                                return element.src || element.dataset.cover || null;
                            }
                        }
                        return null;
                    }
                """)
                
                # 获取页面标题作为备选
                if not video_title:
                    video_title = await page.title()
                
                print("成功通过浏览器获取视频信息")
                
                await browser.close()
                
                return {
                    'platform': 'douyin',
                    'video_id': video_id,
                    'title': video_title or '',
                    'author': author_name or '',
                    'url': final_url,
                    'duration': duration,
                    'thumbnail': thumbnail or '',
                    'description': video_title or '',
                    'upload_date': '',
                    'view_count': 0,
                    'like_count': 0,
                    'comment_count': 0,
                }
                
            except Exception as e:
                self.logger.error(f"使用Playwright获取视频信息失败: {e}")
                try:
                    await browser.close()
                except:
                    pass  # 浏览器可能未完全初始化
                return None
    
    async def download_video(self, url: str, output_path: str, use_cookies: bool = True) -> bool:
        """下载视频"""
        try:
            # 检查是否为短链接，如果是则先转换为长链接
            if 'v.douyin.com' in url or 'v.kuaishou.com' in url or 'gifshow.com' in url:
                self.logger.info(f"检测到短链接，尝试转换: {url}")
                resolved_url = await self.resolve_short_url(url)
                if resolved_url:
                    url = resolved_url
                    self.logger.info(f"短链接转换成功，使用长链接: {url}")
                else:
                    self.logger.warning(f"短链接转换失败，继续使用原链接: {url}")
            
            # 确保输出目录存在
            output_dir = Path(output_path).parent
            output_dir.mkdir(parents=True, exist_ok=True)
            
            # 检查cookies有效性
            cookies_valid = self.check_cookies_validity() if use_cookies else False
            
            # 如果cookies无效且用户希望使用cookies，尝试刷新cookies
            if use_cookies and not cookies_valid:
                self.logger.info("检测到cookies无效，尝试自动刷新...")
                await self.refresh_cookies_if_needed()
                # 重新检查cookies有效性
                cookies_valid = self.check_cookies_validity()
            
            # 尝试使用cookies下载视频
            if use_cookies and cookies_valid:
                # 使用更完整的Douyin特定参数
                ydl_opts_with_cookies = {
                    'outtmpl': output_path,
                    'format': self.config.video_quality,
                    'noplaylist': True,
                    'quiet': True,
                    'no_warnings': True,
                    'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    'compat_opts': ['no-live-chat'],
                    'extractor_args': {
                        'douyin': {
                            'app_version': '23.7.0',
                            'version_code': '2370',
                            'device_id': '7308818885086243331',  # 模拟设备ID
                            'iid': '7308818885086243331',  # 模拟安装ID
                            'openudid': '123456789abcdef0',  # 模拟openudid
                        }
                    },
                }
                
                temp_cookie_file = None
                temp_cookie_file = self._convert_json_cookies_to_netscape('douyin_cookies.json')
                if temp_cookie_file:
                    ydl_opts_with_cookies['cookiefile'] = temp_cookie_file
                    # 添加更完整的头部信息，模拟真实浏览器请求
                    ydl_opts_with_cookies['http_headers'] = {
                        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                        'Referer': 'https://www.douyin.com/',
                        'Origin': 'https://www.douyin.com',
                        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                        'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
                        'Accept-Encoding': 'gzip, deflate, br',
                        'Connection': 'keep-alive',
                        'Upgrade-Insecure-Requests': '1',
                        'Sec-Fetch-Dest': 'document',
                        'Sec-Fetch-Mode': 'navigate',
                        'Sec-Fetch-Site': 'none',
                        'Cache-Control': 'max-age=0',
                    }
                    # 添加额外的请求选项
                    ydl_opts_with_cookies['headers'] = ydl_opts_with_cookies['http_headers']
                
                try:
                    with yt_dlp.YoutubeDL(ydl_opts_with_cookies) as ydl:
                        ydl.download([url])
                    
                    return True
                except Exception as e:
                    self.logger.warning(f"使用cookies下载视频失败: {e}")
                    # 清理临时cookie文件
                    if temp_cookie_file and os.path.exists(temp_cookie_file):
                        try:
                            os.unlink(temp_cookie_file)
                        except:
                            pass
                    # 如果是由于cookies过期导致的错误，尝试自动刷新cookies
                    if "Fresh cookies" in str(e) or "fresh cookies" in str(e):
                        self.logger.info("检测到cookies过期错误，尝试强制刷新...")
                        # 强制刷新cookies，即使本地检查认为有效
                        success = await self.refresh_cookies_if_needed(force_refresh=True)
                        if success:
                            # 刷新成功后，再次尝试使用cookies
                            temp_cookie_file = self._convert_json_cookies_to_netscape('douyin_cookies.json')
                            if temp_cookie_file:
                                # 使用更完整的Douyin特定参数
                                ydl_opts_with_cookies['cookiefile'] = temp_cookie_file
                                # 添加更完整的头部信息
                                ydl_opts_with_cookies['http_headers'] = {
                                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                                    'Referer': 'https://www.douyin.com/',
                                    'Origin': 'https://www.douyin.com',
                                    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                                    'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
                                    'Accept-Encoding': 'gzip, deflate, br',
                                    'Connection': 'keep-alive',
                                    'Upgrade-Insecure-Requests': '1',
                                    'Sec-Fetch-Dest': 'document',
                                    'Sec-Fetch-Mode': 'navigate',
                                    'Sec-Fetch-Site': 'none',
                                    'Cache-Control': 'max-age=0',
                                }
                                ydl_opts_with_cookies['headers'] = ydl_opts_with_cookies['http_headers']
                                
                                try:
                                    with yt_dlp.YoutubeDL(ydl_opts_with_cookies) as ydl:
                                        ydl.download([url])
                                    
                                    return True
                                except Exception as retry_e:
                                    self.logger.warning(f"重试使用cookies下载视频也失败: {retry_e}")
                                finally:
                                    # 清理临时cookie文件
                                    if temp_cookie_file and os.path.exists(temp_cookie_file):
                                        try:
                                            os.unlink(temp_cookie_file)
                                        except:
                                            pass
                    
                    # 尝试不使用cookies下载
                    self.logger.info("尝试不使用cookies下载视频...")
            
            # 如果使用cookies失败或不使用cookies，尝试不使用cookies下载
            ydl_opts_no_cookies = {
                'outtmpl': output_path,
                'format': self.config.video_quality,
                'noplaylist': True,
                'quiet': True,
                'no_warnings': True,
                'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'compat_opts': ['no-live-chat'],
                'extractor_args': {
                    'douyin': {
                        'app_version': '23.7.0',
                        'version_code': '2370',
                        'device_id': '7308818885086243331',  # 模拟设备ID
                        'iid': '7308818885086243331',  # 模拟安装ID
                        'openudid': '123456789abcdef0',  # 模拟openudid
                    }
                },
                'http_headers': {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    'Referer': 'https://www.douyin.com/',
                    'Origin': 'https://www.douyin.com',
                    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.9',
                    'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
                    'Accept-Encoding': 'gzip, deflate, br',
                    'Connection': 'keep-alive',
                    'Upgrade-Insecure-Requests': '1',
                    'Sec-Fetch-Dest': 'document',
                    'Sec-Fetch-Mode': 'navigate',
                    'Sec-Fetch-Site': 'none',
                    'Cache-Control': 'max-age=0',
                },
            }
            
            with yt_dlp.YoutubeDL(ydl_opts_no_cookies) as ydl:
                ydl.download([url])
            
            return True
        except Exception as e:
            self.logger.error(f"下载视频失败: {e}")
            # 如果是由于cookies过期导致的错误，尝试自动刷新cookies
            if "Fresh cookies" in str(e) or "fresh cookies" in str(e):
                self.logger.info("检测到cookies过期错误，尝试自动刷新...")
                await self.refresh_cookies_if_needed()
            
            # 最后尝试使用 Playwright 直接下载视频
            print("尝试使用浏览器自动化方法下载视频...")
            playwright_result = await self.download_video_with_playwright(url, output_path)
            if playwright_result:
                self.logger.info("成功通过浏览器自动化方法下载视频")
                return True
            
            return False
    
    async def download_video_with_playwright(self, url: str, output_path: str) -> bool:
        """使用 Playwright 直接下载视频作为备用方法"""
        try:
            from playwright.async_api import async_playwright
            import aiohttp
            import json
        except ImportError:
            self.logger.error("Playwright 未安装，无法使用浏览器自动化方法下载视频")
            return False
        
        # 加载 cookies
        cookies = []
        if os.path.exists('douyin_cookies.json'):
            try:
                with open('douyin_cookies.json', 'r', encoding='utf-8') as f:
                    cookies = json.load(f)
            except Exception as e:
                self.logger.warning(f"加载 cookies 失败: {e}")
        
        async with async_playwright() as p:
            try:
                print("正在启动浏览器以下载视频...")
                self.logger.info("启动浏览器以下载视频")
                
                browser = await p.chromium.launch(
                    headless=True,
                    args=[
                        '--disable-blink-features=AutomationControlled',
                        '--disable-dev-shm-usage',
                        '--no-sandbox',
                        '--disable-blink-features',
                        '--disable-extensions',
                        '--disable-features=VizDisplayCompositor'
                    ]
                )
                
                context = await browser.new_context(
                    viewport={'width': 1366, 'height': 768},
                    user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
                )
                
                # 添加 cookies
                if cookies:
                    await context.add_cookies(cookies)
                
                await context.add_init_script("""
                    Object.defineProperty(navigator, 'webdriver', {
                        get: () => undefined,
                    });
                """)
                
                page = await context.new_page()
                
                print(f"正在访问视频页面: {url}")
                await page.goto(url, wait_until='domcontentloaded')
                
                # 等待页面加载
                await page.wait_for_timeout(10000)
                
                # 尝试获取视频 URL
                video_url = await page.evaluate("""
                    () => {
                        // 尝试多种方式获取视频 URL
                        
                        // 方法 1: 从 video 元素获取
                        const videoElement = document.querySelector('video');
                        if (videoElement && videoElement.src) {
                            return videoElement.src;
                        }
                        
                        // 方法 2: 从 video 元素的 source 标签获取
                        const sourceElement = document.querySelector('video source');
                        if (sourceElement && sourceElement.src) {
                            return sourceElement.src;
                        }
                        
                        // 方法 3: 从页面全局变量获取
                        if (window.__INITIAL_STATE__) {
                            try {
                                const state = window.__INITIAL_STATE__;
                                // 尝试从 state 中提取视频 URL
                                const stateStr = JSON.stringify(state);
                                const urlMatch = stateStr.match(/https?:\\/\\/[^"']+\\.mp4[^"']*/);
                                if (urlMatch) {
                                    return urlMatch[0].replace(/\\\\/g, '');
                                }
                            } catch (e) {
                                console.log('Error extracting from __INITIAL_STATE__:', e);
                            }
                        }
                        
                        // 方法 4: 从 _SSR_HYDRATED_DATA 获取
                        if (window._SSR_HYDRATED_DATA) {
                            try {
                                const data = window._SSR_HYDRATED_DATA;
                                const dataStr = JSON.stringify(data);
                                const urlMatch = dataStr.match(/https?:\\/\\/[^"']+\\.mp4[^"']*/);
                                if (urlMatch) {
                                    return urlMatch[0].replace(/\\\\/g, '');
                                }
                            } catch (e) {
                                console.log('Error extracting from _SSR_HYDRATED_DATA:', e);
                            }
                        }
                        
                        // 方法 5: 从所有 script 标签中提取
                        const scripts = document.querySelectorAll('script');
                        for (const script of scripts) {
                            if (script.textContent) {
                                const content = script.textContent;
                                const urlMatch = content.match(/https?:\\/\\/[^"']+\\.mp4[^"']*/);
                                if (urlMatch) {
                                    return urlMatch[0].replace(/\\\\/g, '');
                                }
                            }
                        }
                        
                        // 方法 6: 尝试从页面 HTML 中提取所有可能的 URL
                        const html = document.documentElement.innerHTML;
                        const allUrlMatches = html.match(/https?:\\/\\/[^"']+\\.mp4[^"']*/g);
                        if (allUrlMatches && allUrlMatches.length > 0) {
                            // 返回第一个找到的 URL
                            return allUrlMatches[0].replace(/\\\\/g, '');
                        }
                        
                        return null;
                    }
                """)
                
                if not video_url:
                    print("无法从页面中提取视频 URL")
                    await browser.close()
                    return False
                
                print(f"找到视频 URL: {video_url}")
                
                # 下载视频（带重试机制）
                max_retries = 3
                for retry in range(max_retries):
                    try:
                        print(f"正在下载视频... (尝试 {retry + 1}/{max_retries})")
                        
                        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=300)) as session:
                            async with session.get(video_url, headers={
                                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                                'Referer': 'https://www.douyin.com/',
                                'Accept': '*/*',
                                'Accept-Encoding': 'gzip, deflate, br',
                                'Connection': 'keep-alive',
                            }) as resp:
                                if resp.status == 200:
                                    # 确保输出目录存在
                                    output_dir = Path(output_path).parent
                                    output_dir.mkdir(parents=True, exist_ok=True)
                                    
                                    # 写入文件
                                    with open(output_path, 'wb') as f:
                                        downloaded = 0
                                        async for chunk in resp.content.iter_chunked(8192):
                                            f.write(chunk)
                                            downloaded += len(chunk)
                                    
                                    # 验证文件大小
                                    file_size = Path(output_path).stat().st_size
                                    if file_size > 0:
                                        print(f"视频下载成功，文件大小: {file_size / 1024 / 1024:.2f} MB")
                                        await browser.close()
                                        return True
                                    else:
                                        print(f"下载的文件大小为0，重试...")
                                        raise Exception("文件大小为0")
                                else:
                                    print(f"下载视频失败，HTTP 状态码: {resp.status}")
                                    raise Exception(f"HTTP {resp.status}")
                    
                    except Exception as e:
                        print(f"下载失败 (尝试 {retry + 1}/{max_retries}): {e}")
                        if retry < max_retries - 1:
                            await asyncio.sleep(2)  # 等待2秒后重试
                        else:
                            print(f"下载失败，已达到最大重试次数")
                            await browser.close()
                            return False
                
            except Exception as e:
                self.logger.error(f"使用 Playwright 下载视频失败: {e}")
                try:
                    await browser.close()
                except:
                    pass
                return False
    
    async def batch_download_videos(self, urls: List[str], output_dir: str) -> List[bool]:
        """批量下载视频"""
        tasks = []
        
        for i, url in enumerate(urls):
            output_path = f"{output_dir}/video_{i}.mp4"
            task = self.download_video(url, output_path)
            tasks.append(task)
        
        # 限制并发数
        semaphore = asyncio.Semaphore(self.config.max_download_concurrent)
        
        async def download_with_semaphore(url, output_path):
            async with semaphore:
                return await self.download_video(url, output_path)
        
        download_tasks = []
        for i, url in enumerate(urls):
            output_path = f"{output_dir}/video_{i}.mp4"
            task = download_with_semaphore(url, output_path)
            download_tasks.append(task)
        
        results = await asyncio.gather(*download_tasks, return_exceptions=True)
        
        # 将异常转换为False
        return [r if isinstance(r, bool) else False for r in results]
    
    async def download_video_by_info(self, video_info: Dict, output_dir: str, use_cookies: bool = True) -> Optional[str]:
        """根据视频信息下载视频"""
        import re
        
        # 清理视频标题，使其适合作为文件名
        title = video_info.get('title', video_info['video_id'])
        
        # 移除文件名中不允许的字符（Windows 不允许的字符）
        title = re.sub(r'[<>:"/\\|?*]', '', title)
        
        # 移除多余的空格和特殊字符
        title = re.sub(r'\s+', ' ', title.strip())
        
        # 移除常见的无意义后缀（如 #标签）
        title = re.sub(r'#[\w\u4e00-\u9fa5]+', '', title)
        
        # 再次清理空格
        title = re.sub(r'\s+', ' ', title.strip())
        
        # 限制文件名长度（Windows 文件名最大 255 字符，但建议更短）
        if len(title) > 150:
            title = title[:150]
        
        # 如果清理后标题为空，使用 video_id
        if not title:
            title = video_info['video_id']
        
        # 使用视频标题作为文件名
        filename = f"{title}.mp4"
        output_path = f"{output_dir}/{filename}"
        
        success = await self.download_video(video_info['url'], output_path, use_cookies)
        
        if success:
            return output_path
        else:
            return None

class DouyinHandler:
    """抖音视频处理器"""
    def __init__(self):
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
            'Referer': 'https://www.douyin.com/',
        }
    
    async def clean_url(self, url: str) -> str:
        """清理抖音URL，获取真实视频链接"""
        # 如果是分享链接，需要先解析
        if 'v.douyin.com' in url:
            async with aiohttp.ClientSession() as session:
                try:
                    # 不跟随重定向，获取真实URL
                    async with session.get(url, allow_redirects=False) as resp:
                        if 'Location' in resp.headers:
                            real_url = resp.headers['Location']
                            return real_url
                except Exception as e:
                    print(f"解析抖音短链接失败: {e}")
        
        return url

class KuaishouHandler:
    """快手视频处理器"""
    def __init__(self):
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
            'Referer': 'https://www.kuaishou.com/',
        }
    
    async def clean_url(self, url: str) -> str:
        """清理快手URL"""
        # 快手可能需要特殊的处理
        return url

# 使用示例
async def main():
    async with VideoAcquisition() as va:
        # 示例URL
        url = "https://www.douyin.com/video/xxxxxxxx"  # 替换为实际的抖音视频URL
        
        # 获取视频信息
        info = await va.get_video_info(url)
        if info:
            print(f"视频标题: {info['title']}")
            print(f"作者: {info['author']}")
            print(f"时长: {info['duration']}秒")
            
            # 下载视频
            download_path = await va.download_video_by_info(info, "./downloads")
            if download_path:
                print(f"视频已下载到: {download_path}")
        else:
            print("获取视频信息失败")

if __name__ == "__main__":
    asyncio.run(main())